import type { PartOfSpeech } from '@prisma/client';

export interface SuffixRuleSeed {
  suffix: string;
  pos: PartOfSpeech;
  reliability: number;
  explanationVi: string;
  examples: string[];
  exceptions: string[];
  order: number;
}

/** §7.4 Tab 3 — the suffix table Vietnamese exam takers actually need. */
export const SUFFIX_RULES: SuffixRuleSeed[] = [
  {
    suffix: '-tion',
    pos: 'NOUN',
    reliability: 0.97,
    explanationVi:
      'Biến động từ thành danh từ chỉ hành động hoặc kết quả. Trọng âm luôn rơi vào âm tiết ngay trước -tion.',
    examples: ['education', 'information', 'action', 'protection'],
    exceptions: ['mention (cũng là động từ)'],
    order: 1,
  },
  {
    suffix: '-sion',
    pos: 'NOUN',
    reliability: 0.96,
    explanationVi: 'Giống -tion nhưng đi sau các âm /d/, /s/, /ʒ/: decide → decision.',
    examples: ['decision', 'discussion', 'permission', 'television'],
    exceptions: [],
    order: 2,
  },
  {
    suffix: '-ment',
    pos: 'NOUN',
    reliability: 0.95,
    explanationVi: 'Gắn vào động từ để chỉ hành động hoặc kết quả: move → movement.',
    examples: ['movement', 'development', 'agreement', 'payment'],
    exceptions: ['comment (cũng là động từ)', 'implement (cũng là động từ)'],
    order: 3,
  },
  {
    suffix: '-ness',
    pos: 'NOUN',
    reliability: 0.98,
    explanationVi: 'Gắn vào tính từ để chỉ tính chất: happy → happiness. Chú ý y đổi thành i.',
    examples: ['happiness', 'kindness', 'darkness', 'illness'],
    exceptions: [],
    order: 4,
  },
  {
    suffix: '-ity',
    pos: 'NOUN',
    reliability: 0.94,
    explanationVi: 'Danh từ trừu tượng từ tính từ: able → ability. Trọng âm rơi ngay trước -ity.',
    examples: ['ability', 'security', 'activity', 'reality'],
    exceptions: [],
    order: 5,
  },
  {
    suffix: '-ance / -ence',
    pos: 'NOUN',
    reliability: 0.92,
    explanationVi: 'Danh từ từ động từ hoặc tính từ: important → importance, differ → difference.',
    examples: ['importance', 'difference', 'performance', 'independence'],
    exceptions: [],
    order: 6,
  },
  {
    suffix: '-ship',
    pos: 'NOUN',
    reliability: 0.96,
    explanationVi: 'Chỉ trạng thái hoặc quan hệ: friend → friendship.',
    examples: ['friendship', 'relationship', 'leadership', 'membership'],
    exceptions: [],
    order: 7,
  },
  {
    suffix: '-hood',
    pos: 'NOUN',
    reliability: 0.97,
    explanationVi: 'Chỉ giai đoạn hoặc trạng thái: child → childhood.',
    examples: ['childhood', 'neighbourhood', 'motherhood'],
    exceptions: [],
    order: 8,
  },
  {
    suffix: '-ism',
    pos: 'NOUN',
    reliability: 0.95,
    explanationVi: 'Chỉ chủ nghĩa, học thuyết hoặc hiện tượng: tour → tourism.',
    examples: ['tourism', 'criticism', 'realism'],
    exceptions: [],
    order: 9,
  },
  {
    suffix: '-ist',
    pos: 'NOUN',
    reliability: 0.93,
    explanationVi: 'Chỉ người làm nghề hoặc theo một chủ nghĩa: art → artist.',
    examples: ['artist', 'scientist', 'journalist', 'tourist'],
    exceptions: ['exist (động từ)', 'assist (động từ)'],
    order: 10,
  },
  {
    suffix: '-er / -or',
    pos: 'NOUN',
    reliability: 0.9,
    explanationVi: 'Chỉ người hoặc vật thực hiện hành động: teach → teacher, act → actor.',
    examples: ['teacher', 'actor', 'computer', 'visitor'],
    exceptions: ['answer (động từ)', 'offer (động từ)', 'remember (động từ)'],
    order: 11,
  },
  {
    suffix: '-age',
    pos: 'NOUN',
    reliability: 0.88,
    explanationVi: 'Chỉ hành động, kết quả hoặc tập hợp: store → storage.',
    examples: ['storage', 'package', 'marriage', 'shortage'],
    exceptions: ['manage (động từ)', 'encourage (động từ)'],
    order: 12,
  },
  {
    suffix: '-ful',
    pos: 'ADJECTIVE',
    reliability: 0.97,
    explanationVi: 'Nghĩa là "đầy, có": care → careful. Chỉ có MỘT chữ l.',
    examples: ['careful', 'beautiful', 'useful', 'powerful'],
    exceptions: [],
    order: 13,
  },
  {
    suffix: '-less',
    pos: 'ADJECTIVE',
    reliability: 0.98,
    explanationVi: 'Nghĩa là "không có" — trái nghĩa với -ful: useful ↔ useless.',
    examples: ['useless', 'homeless', 'careless', 'endless'],
    exceptions: ['unless (liên từ)'],
    order: 14,
  },
  {
    suffix: '-ous',
    pos: 'ADJECTIVE',
    reliability: 0.96,
    explanationVi: 'Chỉ tính chất: fame → famous, danger → dangerous.',
    examples: ['famous', 'dangerous', 'nervous', 'delicious'],
    exceptions: [],
    order: 15,
  },
  {
    suffix: '-ive',
    pos: 'ADJECTIVE',
    reliability: 0.93,
    explanationVi: 'Chỉ xu hướng hoặc khả năng: create → creative.',
    examples: ['creative', 'active', 'expensive', 'effective'],
    exceptions: ['drive (động từ)', 'give (động từ)'],
    order: 16,
  },
  {
    suffix: '-al',
    pos: 'ADJECTIVE',
    reliability: 0.9,
    explanationVi: 'Nghĩa "thuộc về": nation → national. Nhưng cũng có danh từ đuôi -al.',
    examples: ['national', 'personal', 'natural', 'digital'],
    exceptions: ['animal (danh từ)', 'hospital (danh từ)', 'arrival (danh từ)'],
    order: 17,
  },
  {
    suffix: '-ic',
    pos: 'ADJECTIVE',
    reliability: 0.94,
    explanationVi: 'Nghĩa "thuộc về, mang tính": history → historic. Trọng âm rơi ngay trước -ic.',
    examples: ['historic', 'economic', 'basic', 'scientific'],
    exceptions: ['music (danh từ)', 'traffic (danh từ)'],
    order: 18,
  },
  {
    suffix: '-able / -ible',
    pos: 'ADJECTIVE',
    reliability: 0.96,
    explanationVi: 'Nghĩa "có thể được": accept → acceptable, access → accessible.',
    examples: ['acceptable', 'comfortable', 'possible', 'responsible'],
    exceptions: ['table (danh từ)', 'vegetable (danh từ)'],
    order: 19,
  },
  {
    suffix: '-y',
    pos: 'ADJECTIVE',
    reliability: 0.85,
    explanationVi: 'Biến danh từ thành tính từ: rain → rainy, sun → sunny.',
    examples: ['rainy', 'sunny', 'noisy', 'healthy'],
    exceptions: ['country (danh từ)', 'city (danh từ)', 'family (danh từ)'],
    order: 20,
  },
  {
    suffix: '-ish',
    pos: 'ADJECTIVE',
    reliability: 0.9,
    explanationVi: 'Nghĩa "hơi, gần giống" hoặc chỉ quốc tịch: child → childish, Spain → Spanish.',
    examples: ['childish', 'selfish', 'reddish', 'Spanish'],
    exceptions: ['finish (động từ)', 'publish (động từ)', 'punish (động từ)'],
    order: 21,
  },
  {
    suffix: '-ent / -ant',
    pos: 'ADJECTIVE',
    reliability: 0.88,
    explanationVi: 'Chỉ tính chất: differ → different, import → important.',
    examples: ['different', 'important', 'confident', 'pleasant'],
    exceptions: ['student (danh từ)', 'assistant (danh từ)', 'restaurant (danh từ)'],
    order: 22,
  },
  {
    suffix: '-ly',
    pos: 'ADVERB',
    reliability: 0.92,
    explanationVi:
      'Dấu hiệu trạng từ rõ nhất: quick → quickly. Nhưng cẩn thận, một số tính từ cũng kết thúc bằng -ly.',
    examples: ['quickly', 'carefully', 'slowly', 'happily'],
    exceptions: ['friendly (tính từ)', 'lovely (tính từ)', 'lonely (tính từ)', 'likely (tính từ)'],
    order: 23,
  },
  {
    suffix: '-ward(s)',
    pos: 'ADVERB',
    reliability: 0.95,
    explanationVi: 'Chỉ hướng: back → backwards, for → forward.',
    examples: ['backwards', 'forward', 'upward', 'homeward'],
    exceptions: [],
    order: 24,
  },
  {
    suffix: '-wise',
    pos: 'ADVERB',
    reliability: 0.94,
    explanationVi: 'Chỉ cách thức hoặc phương diện: clock → clockwise, other → otherwise.',
    examples: ['clockwise', 'otherwise', 'likewise'],
    exceptions: ['wise (tính từ)'],
    order: 25,
  },
  {
    suffix: '-ize / -ise',
    pos: 'VERB',
    reliability: 0.96,
    explanationVi: 'Biến danh từ hoặc tính từ thành động từ: modern → modernize. Anh-Mỹ viết -ize, Anh-Anh thường -ise.',
    examples: ['modernize', 'realize', 'organize', 'apologize'],
    exceptions: ['size (danh từ)', 'exercise (cũng là danh từ)'],
    order: 26,
  },
  {
    suffix: '-ify',
    pos: 'VERB',
    reliability: 0.97,
    explanationVi: 'Nghĩa "làm cho trở nên": simple → simplify, beauty → beautify.',
    examples: ['simplify', 'beautify', 'identify', 'clarify'],
    exceptions: [],
    order: 27,
  },
  {
    suffix: '-en',
    pos: 'VERB',
    reliability: 0.89,
    explanationVi: 'Nghĩa "làm cho": wide → widen, short → shorten.',
    examples: ['widen', 'shorten', 'strengthen', 'darken'],
    exceptions: ['often (trạng từ)', 'garden (danh từ)', 'children (danh từ)'],
    order: 28,
  },
  {
    suffix: '-ate',
    pos: 'VERB',
    reliability: 0.87,
    explanationVi: 'Thường là động từ: active → activate. Nhưng một số tính từ cũng có đuôi -ate.',
    examples: ['activate', 'celebrate', 'communicate', 'educate'],
    exceptions: ['private (tính từ)', 'accurate (tính từ)', 'climate (danh từ)'],
    order: 29,
  },
  {
    suffix: 'en- / em-',
    pos: 'VERB',
    reliability: 0.93,
    explanationVi: 'Tiền tố tạo động từ, nghĩa "làm cho, đưa vào": able → enable, power → empower.',
    examples: ['enable', 'empower', 'encourage', 'embrace'],
    exceptions: ['energy (danh từ)', 'empty (tính từ)'],
    order: 30,
  },
];
